### ISSUE TITLE
missing yolov3-custom_7000.weights file

### ISSUE THREAD

**Issue by hope404alive** [FatimaSidra/Helmet-and-Number-Plate-Detection-and-Recognition#1]
Please add yolov3-custom_7000.weights as it is missing . The project looks good

**Comment by FatimaSidra** [comment]
Here's link to the yolov3-custom_7000.weights.
https://drive.google.com/file/d/17DWQ1WfYHxYD_wab2OQybHwRaDDGN54K/view?usp=sharing
